### PR TITLE
Add assume yes option

### LINKED ISSUE #7: Flag to "assume yes" to questions
It would be nice if there was a "-y" or "--assume-yes" flag that would automatically answer all prompts with "yes". This would make `bunup` easier to use in automation.

### PR DESCRIPTION
**Pull request by shanecav84**
Fixes #7

### CODE REVIEW

**Comment by shanecav84** [comment]
When updating a single gem, we want to exit immediately when the user doesn't want to update the major version. `SystemExit` is what's raised by `exit` so it's used explicitly at that point. When updating multiple gems, we *don't* want to immediately exit at that point so we catch the exit. See `::Bunup::CLI::handle_system_exit`

**Comment by sbleon** [comment]
If we're updating a single gem, and the user answers "no", couldn't we just
call `next` since it would be the last gem in the update loop? I guess I
don't understand why a single gem update should be treated differently than
a multi-gem update.

**Comment by shanecav84** [comment]
> If we're updating a single gem, and the user answers "no", couldn't we just call `next`

Yes, though I think that would add additional complexity considering the pattern I've set up.

> I guess I don't understand why a single gem update should be treated differently than a multi-gem update.

There are a few sub-routines that should halt if they fail: declined major version updates, updating a gem that's already up-to-date, and updating a gem that's version constrained by another gem. For single gem updates, a sub-routine failing should halt the whole program; for multi-gem updates, the sub-routine should only halt for the relevant gem and continue running for other gems. The pattern leans on `SystemExit` determine if the whole command should halt (and print a message). `::Bunup::CLI#handle_system_exit` catches exits for particular sub-routines, prints their error message, then determines if the whole program should halt. There's one method to handle all of that. Adding a conditional in the `@gem` loop would be an additional error handling pattern on top of the one that exists.

I think that using `SystemExit` for control flow in a CLI makes sense when a sub-routine is indicating that it's reached a point that should halt further progress. It's up to the state of the calling object to determine if the whole program should stop or if just that sub-routine should stop.

**Comment by sbleon** [comment]
Thanks for elaborating on that! The one thing I'm still not clear about is
why we need to treat single-gem updates and multi-gem updates differently
here <https://github.com/singlebrook/bunup/blob/master/lib/bunup/cli.rb#L73>.
Consider:

1. A single-gem major update. The user declines the update. `bunup` should
print some feedback and do no more updates. Since it's a single-gem update,
there are no more gems to update, and it will do no more updates whether or
not we swallow `SystemExit`.
2. A multi-gem update. The user declines a major update. `bunup` should
print some feedback and do no more updates. In this case we have to raise
the exception to prevent further updates.

So, why can't we always `raise exception`, with no condition on it?

Sorry if I'm harping on this. I'm just curious about it.

**Comment by shanecav84** [comment]
> So, why can't we always `raise exception`, with no condition on it?

Considering just major version updates, then using `next unless update_major_version?` in the loop without a `::SystemExit` call would make perfect sense, but `raise exception unless bunup_many?` is also handling `::SystemExit` raised elsewhere.

**Comment by sbleon** [comment]
Oh, boy, did I confuse myself earlier. When I said that a declination in a
multi-gem update should stop all further updating, I was wrong. That's
certainly not how I want it to work. By that logic, we should swallow all
SystemExit errors from major version update questions.

I think what you're getting at is that when an earlier step of the process
(e.g. `update`) fails, you don't want to proceed to later steps of the
process (e.g. `commit`). But I don't think you need to re-raise SystemExit
to make that happen. Any SystemExit raised in the `@gems.each` loop will
cause a jump down to the `rescue`, which will then call `next`, which will
exit the program. in the case of a single-gem update. But maybe in that
scenario, the exit code would be `true`, but we want it to be `false` if a
single-gem update fails.

Anyway, it's working well as is, and the code is very readable, so there's
no good reason to change it. I'll shut up now.

**Pull request merged**
